### PR TITLE
Fixed settings and urls

### PR DESCRIPTION
**Pull request by chdefrene**
* Removed password requirements for testing
* Added new apps and urls

### CODE REVIEW

**Comment by trmdy** [comment]
Why have you removed the password requirements for the default settings?

**Comment by chdefrene** [comment]
I removed the password requirements so we can have simpler test passwords. They will be reinstated later.

**Comment by chdefrene** [comment]
The intention was so that we could have easy password while testing. I'll change it to disable only when debug is true

**Review by trmdy — APPROVED** [review]
Looks good. Conflicts should be resolved by additive merging (i.e. everything should be kept).

**Pull request merged**
