### PR TITLE
Feature/heroku deployment

### LINKED ISSUE #166: Set up Sentry

### PR DESCRIPTION
**Pull request by alexaor**
Sets up automatic deployment to Heroku instance.  (WIP Status: Connecting to redis and fix chat-service)

Closes #166 

Summary of changes
- removes AWS dependencies
- Add whitenoise for serving static files on heroku
- Add dj-database-url to manage db connection on heroku
- Add django-redis-cache to manage redis connection on heroku
- Rename prod to stating for settings
- Add configuration required for heroku in staging settings
- Configure automatic deployment and migration on develop branch changes

ToDos

- [x] Deploy webapp to dyno instance
- [x] Connect to postgres service
- [x] Serving static files
- [x] Connect to Redis service
- [x] Storing static files
- [ ] Fix websocket connection for chat

### CODE REVIEW

**Comment by trmdy** [comment]
Does this include a bunch of other code as well?

**Comment by alexaor** [comment]
@tOgg1 Branched out from https://github.com/KSG-IT/ksg-nett/pull/176, which again branches out form another branch, but i will unmark it as a draft when the diff only contains branch relevant changes.

**Comment by alexaor** [comment]
Dear god does someone know what we need to get the damn websockets to connect in the chat and not hit a `404`

**Comment by alexaor** [comment]
Scrapping getting websocket to function on heorku. Will clean up settingsfile and Procfile before re-requesting review

**Pull request closed without merging**
