### PR TITLE
WIP: Initialize SociBankAccount upon creation of a User.

### PR DESCRIPTION
**Pull request by holtetx**
Signals added so that when you create a user object, a SociBankAccount is associated with the user object.

### CODE REVIEW

**Comment by holtetx** [comment]
Could need some help sorting out the test conflict. 
[This](https://stackoverflow.com/questions/21458387/transactionmanagementerror-you-cant-execute-queries-until-the-end-of-the-atom) could be a good start.

**Comment by alexaor** [comment]
Might be relevant [link](https://stackoverflow.com/questions/44450533/difference-between-testcase-and-transactiontestcase-classes-in-django-test)

**Comment by trmdy** [comment]
The error message is a bit of a red herring.

The issue is due to the fact that when you create a new SociBankAccount using `SociBankAccountFactory`, a related user will automatically be created by the sub factory relationship, which then will try to create a new soci bank account for the user; breaking the unique constraint. 

The specific error message thrown is then due to the reasons mentioned in the articles you refer to.

So there are two fixes to this issue, both of which should be implemented as they address the two competing locations. The first one is adding `django_get_or_create` in `SociBankAccountFactory.Meta`, and the second is ensuring the signal-handler does not attempt to create a new soci bank account if the user already has one. Some more test cases to verify and lock the functionality might be necessary.

The following diff should solve both issues:

```
diff --git a/economy/tests/factories.py b/economy/tests/factories.py
index de9a251..2a0cac8 100644
--- a/economy/tests/factories.py
+++ b/economy/tests/factories.py
@@ -12,6 +12,7 @@ from users.tests.factories import UserFactory
 class SociBankAccountFactory(DjangoModelFactory):
     class Meta:
         model = SociBankAccount
+        django_get_or_create = ("user",)
 
     user = SubFactory(UserFactory)
     balance = 0
diff --git a/users/signals.py b/users/signals.py
index b712e74..571efbe 100644
--- a/users/signals.py
+++ b/users/signals.py
@@ -6,6 +6,8 @@ from economy.models import SociBankAccount
 
 
 @receiver(signals.post_save, sender=User)
-def create_soci_bank_account(sender, instance, created, **kwargs):
-    if created:
-        SociBankAccount.objects.create(user=instance)
\ No newline at end of file
+def create_soci_bank_account(sender, instance: User, created, **kwargs):
+    # We use getattr here as accessing the field directly when the relation does not
+    # exist will throw an error.
+    if created and getattr(instance, "bank_account", None) is not None:
+        SociBankAccount.objects.create(user=instance)
```

**Comment by holtetx** [comment]
@tOgg1 seems like it worked! 🕺 thanks!

**Review by alexaor — APPROVED** [review]

**Comment by alexaor** [comment]
Great work @Lekesoldat, and thanks again @tOgg1!

**Pull request merged**
